# Generated by Django 6.0.2 on 2026-05-10 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artwork_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='teacher_workshop',
            new_name='workshop',
        ),
        migrations.AddField(
            model_name='artwork',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.person'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.gallery'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='material',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
